---
on:
  push:
    branches:
      - main

jobs:
  terragrunt-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hagzag/dind-aws-cli:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run terragrunt command
        run: docker --version
